### ISSUE TITLE
Error in untested tutorial Markdown file

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#6308]
There is a Markdown currently called `data-management.md`, soon to be renamed to `date-picker-data.md`, that is not being tested. I accidentally included it in the list of tests in `tools/md-tests/src/lib.rs`, and it results in [a few errors](https://github.com/unicode-org/icu4x/actions/runs/13912195101/job/38928549829?pr=6305#step:6:1700). Ex:

```
---- tools/md-tests/src/lib.rs - tutorials::data_management_md (line 176) stdout ----
error[E0412]: cannot find type `Gregorian` in this scope
 --> tools/md-tests/src/lib.rs:177:43
  |
3 | let date_formatter = TypedDateFormatter::<Gregorian>::try_new_with_length(
  |                                           ^^^^^^^^^ not found in this scope
  |
help: you might be missing a type parameter
  |
2 | fn main() { #[allow(non_snake_case)] fn _doctest_main_tools_md_tests_src_lib_rs_176_0<Gregorian>() {
  |                                                                                      +++++++++++

...
```

**Comment by sffc** [comment]
We should make sure that all of our tutorial md files are being tested.

**Comment by robertbastian** [comment]
This tutorial is not easy to test in CI. The code snippets are additive, so they don't compiled individually. I tested this when I wrote it, and because we're not breaking semver, it still works.
