### ISSUE TITLE
Compilation errors after updating zerovec to 0.11.5

### ISSUE THREAD

**Issue by joelchen** [unicode-org/icu4x#7190]
After updating zerovec (nested dependency from url > idna > idna_adapter > icu_normalizer/icu_properties) from 0.11.4 to 0.11.5, my project's compilation failed with the following errors:
```
error[E0432]: unresolved import `zerovec::ZeroMap`
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/icu_properties-2.0.1/src/provider/names.rs:20:27
    |
 20 | use zerovec::{VarZeroVec, ZeroMap, ZeroVec};
    |                           ^^^^^^^ no `ZeroMap` in the root
    |
note: found an item that was configured out
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zerovec-0.11.5/src/lib.rs:241:26
    |
240 | #[cfg(feature = "alloc")]
    |       ----------------- the item is gated behind the `alloc` feature
241 | pub use crate::map::map::ZeroMap;
    |                          ^^^^^^^

   Compiling tracing v0.1.41
error[E0433]: failed to resolve: could not find `maps` in `zerovec`
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/icu_properties-2.0.1/src/props.rs:244:5
    |
244 |     #[zerovec::make_ule(GeneralCategoryULE)]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `maps` in `zerovec`
    |
note: found an item that was configured out
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zerovec-0.11.5/src/lib.rs:261:9
    |
260 | #[cfg(feature = "alloc")]
    |       ----------------- the item is gated behind the `alloc` feature
261 | pub mod maps {
    |         ^^^^
    = note: this error originates in the attribute macro `zerovec::make_ule` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `ZeroMap` in `zerovec`
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/icu_properties-2.0.1/src/provider.rs:155:5
    |
155 |     impl_property_name_long_canonical_combining_class_v1!(Baked);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `ZeroMap` in `zerovec`
    |
note: found an item that was configured out
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zerovec-0.11.5/src/lib.rs:241:26
    |
240 | #[cfg(feature = "alloc")]
    |       ----------------- the item is gated behind the `alloc` feature
241 | pub use crate::map::map::ZeroMap;
    |                          ^^^^^^^
    = note: this error originates in the macro `impl_property_name_long_canonical_combining_class_v1` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `ZeroMap` in `zerovec`
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/icu_properties-2.0.1/src/provider.rs:182:5
    |
182 |     impl_property_name_short_canonical_combining_class_v1!(Baked);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `ZeroMap` in `zerovec`
    |
note: found an item that was configured out
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zerovec-0.11.5/src/lib.rs:241:26
    |
240 | #[cfg(feature = "alloc")]
    |       ----------------- the item is gated behind the `alloc` feature
241 | pub use crate::map::map::ZeroMap;
    |                          ^^^^^^^
    = note: this error originates in the macro `impl_property_name_short_canonical_combining_class_v1` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by joelchen** [comment]
As the error states, ZeroMap is gated behind `alloc` feature, so https://github.com/unicode-org/icu4x/blob/72e94a5baa4bc7840b27eae48cc9364fc018a483/components/normalizer/Cargo.toml#L31 and https://github.com/unicode-org/icu4x/blob/72e94a5baa4bc7840b27eae48cc9364fc018a483/components/properties/Cargo.toml#L26 should include `alloc` feature in the zerovec dependency? @Manishearth @robertbastian

**Comment by kevinji** [comment]
I am also seeing the following compile errors:
```
error[E0412]: cannot find type `String` in module `$crate::_internal`
   --> /root/.cargo/registry/src/index.crates.io-dd9f5ed54ffb646d/icu_locale_core-2.0.0/src/data.rs:104:1
    |
104 | impl_writeable_for_each_subtag_str_no_test!(DataLocale, selff, selff.script.is_none() && selff.region.is_none() && selff.variant.is_none() && selff.subdivision.is_none() => selff.language.write_to_string());
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `$crate::_internal`
    |
note: found an item that was configured out
   --> /root/.cargo/registry/src/index.crates.io-dd9f5ed54ffb646d/writeable-0.6.2/src/lib.rs:145:28
    |
145 |     pub use alloc::string::String;
    |                            ^^^^^^
note: the item is gated behind the `alloc` feature
   --> /root/.cargo/registry/src/index.crates.io-dd9f5ed54ffb646d/writeable-0.6.2/src/lib.rs:144:11
    |
144 |     #[cfg(feature = "alloc")]
    |           ^^^^^^^^^^^^^^^^^
    = note: this error originates in the macro `writeable::impl_display_with_writeable` which comes from the expansion of the macro `impl_writeable_for_each_subtag_str_no_test` (in Nightly builds, run with -Z macro-backtrace for more info)
```
Can we yank the cargo releases from #7180?

**Comment by Manishearth** [comment]
This ought to be fixed by https://github.com/unicode-org/icu4x/pull/7191

In the meantime, the fix is to just run `cargo update`, I think.

**Comment by Manishearth** [comment]
Yeah, the locale_core issue will be fixed by #7191 

Unfortunately I'm not sure if we have a good fix for the zeromap thing on our end: just `cargo update` icu_properties. It is `icu_properties 2.0` that is buggy around the alloc feature.

**Comment by Manishearth** [comment]
Unfortunately yanking can't fix this problem, it's a problem that'll only happen for existing lockfiles (new dependencies will pull in the latest anyway).

**Comment by Manishearth** [comment]
The core issue is fixed. People experiencing this should run `cargo update` for any ICU4X crates still stuck on 2.0
