### ISSUE TITLE
1.3 doesn't build with zerovec 0.9

### ISSUE THREAD

**Issue by robertbastian** [unicode-org/icu4x#4105]
This is a problem for users updating from 1.2 to 1.3.

```toml
[dependencies]
icu_collections = "1.3.0"
zerovec = "0.9" # or 0.9 exists in lock file
```

```
error[E0433]: failed to resolve: could not find `varule` in `zerovec`
  --> /usr/local/google/home/robertbastian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/icu_collections-1.3.0/src/codepointinvliststringlist/mod.rs:35:16
   |
35 |     #[zerovec::varule(CodePointInversionListULE)]
   |                ^^^^^^ could not find `varule` in `zerovec`
...
```

**Comment by robertbastian** [comment]
cc @sffc

**Comment by robertbastian** [comment]
Ah that doesn't actually repro. I've encountered the issue with this lock file: https://github.com/houseabsolute/omegasort/blob/master/Cargo.lock

**Comment by robertbastian** [comment]
Fixed with the 1.3.2 release.
