### PR TITLE
Avoid using derive on autogenerated packed types, bump zerovec-derive to 0.9.3

### LINKED ISSUE #3060: Compile error with recent nightly toolchain
rustc version: `rustc 1.69.0-nightly (dc1d9d50f 2023-01-31)`

Reproduce: run `cargo test` at the root directory. (Maybe `rust-toolchain` should be deleted first.)
```
error[E0161]: cannot move a value of type `str`
  --> utils/zerovec/derive/examples/make_var.rs:10:1
   |
10 | #[make_varule(VarStructULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the size of `str` cannot be statically determined
   |
   = note: this error originates in the attribute macro `make_varule` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `self.c` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:10:1
   |
10 | #[make_varule(VarStructULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `self.c` has type `str`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `other.c` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:10:1
   |
10 | #[make_varule(VarStructULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `other.c` has type `str`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0161]: cannot move a value of type `str`
  --> utils/zerovec/derive/examples/make_var.rs:20:1
   |
20 | #[make_varule(VarStructOutOfOrderULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the size of `str` cannot be statically determined
   |
   = note: this error originates in the attribute macro `make_varule` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `self.b` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:20:1
   |
20 | #[make_varule(VarStructOutOfOrderULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `self.b` has type `str`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `other.b` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:20:1
   |
20 | #[make_varule(VarStructOutOfOrderULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `other.b` has type `str`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0161]: cannot move a value of type `VarZeroSlice<str>`
  --> utils/zerovec/derive/examples/make_var.rs:31:1
   |
31 | #[make_varule(VarTupleStructULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the size of `VarZeroSlice<str>` cannot be statically determined
   |
   = note: this error originates in the attribute macro `make_varule` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `self` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:31:1
   |
31 | #[make_varule(VarTupleStructULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `self.2` has type `VarZeroSlice<str>`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `other` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:31:1
   |
31 | #[make_varule(VarTupleStructULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `other.2` has type `VarZeroSlice<str>`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0161]: cannot move a value of type `VarZeroSlice<str>`
  --> utils/zerovec/derive/examples/make_var.rs:36:1
   |
36 | #[make_varule(NoKVULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^ the size of `VarZeroSlice<str>` cannot be statically determined
   |
   = note: this error originates in the attribute macro `make_varule` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `self` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:36:1
   |
36 | #[make_varule(NoKVULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `self.2` has type `VarZeroSlice<str>`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `other` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:36:1
   |
36 | #[make_varule(NoKVULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `other.2` has type `VarZeroSlice<str>`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0161]: cannot move a value of type `VarZeroSlice<str>`
  --> utils/zerovec/derive/examples/make_var.rs:42:1
   |
42 | #[make_varule(NoOrdULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^ the size of `VarZeroSlice<str>` cannot be statically determined
   |
   = note: this error originates in the attribute macro `make_varule` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `self` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:42:1
   |
42 | #[make_varule(NoOrdULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `self.2` has type `VarZeroSlice<str>`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `other` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:42:1
   |
42 | #[make_varule(NoOrdULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `other.2` has type `VarZeroSlice<str>`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0161]: cannot move a value of type `MultiFieldsULE`
  --> utils/zerovec/derive/examples/make_var.rs:48:1
   |
48 | #[make_varule(MultiFieldStructULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the size of `MultiFieldsULE` cannot be statically determined
   |
   = note: this error originates in the attribute macro `make_varule` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `self.unsized_fields` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:48:1
   |
48 | #[make_varule(MultiFieldStructULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `self.unsized_fields` has type `MultiFieldsULE`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `other.unsized_fields` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:48:1
   |
48 | #[make_varule(MultiFieldStructULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `other.unsized_fields` has type `MultiFieldsULE`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0161]: cannot move a value of type `MultiFieldsULE`
  --> utils/zerovec/derive/examples/make_var.rs:62:1
   |
62 | #[make_varule(MultiFieldTupleULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the size of `MultiFieldsULE` cannot be statically determined
   |
   = note: this error originates in the attribute macro `make_varule` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `self` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:62:1
   |
62 | #[make_varule(MultiFieldTupleULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `self.2` has type `MultiFieldsULE`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0507]: cannot move out of `other` which is behind a shared reference
  --> utils/zerovec/derive/examples/make_var.rs:62:1
   |
62 | #[make_varule(MultiFieldTupleULE)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `other.2` has type `MultiFieldsULE`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0161, E0507.
For more information about an error, try `rustc --explain E0161`.
error: could not compile `zerovec-derive` due to 21 previous errors
```

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #3060

Introduced by https://github.com/rust-lang/rust/pull/104429

### CODE REVIEW

**Comment by robertbastian** [comment]
Merge. I've kept versioning of foo and foo-derive in sync, probably want to bump zerovec as well.

**Review by robertbastian — APPROVED** [review]

**Review by sffc — COMMENTED** [review]
lgtm
