### ISSUE TITLE
Potential `tinystr` collision preventing build in ICU4X 2.0 beta

### ISSUE THREAD

**Issue by nekevss** [unicode-org/icu4x#5899]
When trying to migrate `temporal_rs` to the `icu_calendar` v2 beta alongside `tinystr` v0.8.0, the below error is an example of a few errors that are blocking the build.

```txt

error[E0308]: mismatched types
   --> src/components/calendar.rs:297:22
    |
297 |             Some(Era(fields.era_year.era.0)),
    |                  --- ^^^^^^^^^^^^^^^^^^^^^ expected `tinystr::ascii::TinyAsciiStr<16>`, found `tinystr::TinyAsciiStr<16>`
    |                  |
    |                  arguments to this struct are incorrect
    |
    = note: `tinystr::TinyAsciiStr<16>` and `tinystr::ascii::TinyAsciiStr<16>` have similar names, but are actually distinct types
note: `tinystr::TinyAsciiStr<16>` is defined in crate `tinystr`
   --> /home/nekevss/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tinystr-0.8.0/src/ascii.rs:14:1
    |
14  | pub struct TinyAsciiStr<const N: usize> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: `tinystr::ascii::TinyAsciiStr<16>` is defined in crate `tinystr`
   --> /home/nekevss/.cargo/git/checkouts/icu4x-5b22b8195fc85e4e/9cb01e4/utils/tinystr/src/ascii.rs:14:1
    |
14  | pub struct TinyAsciiStr<const N: usize> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `tinystr` are being used?
note: tuple struct defined here
   --> /home/nekevss/.cargo/git/checkouts/icu4x-5b22b8195fc85e4e/9cb01e4/components/calendar/src/types.rs:27:12
    |
27  | pub struct Era(pub TinyStr16);
    |            ^^^

```

A couple notes for things I tried / checked:

  - Only `tinystr` v0.8.0 is in the Cargo.lock
  - The `Era::from(TinyStr16)` also appears to cause this error

For the snippet: 

```rust
let era = tinystr!(16, "reiwa");
let era: Era = TinyStr16::from_str(fields.era_year.era.0.as_str()).expect("value").into();
```

The below compile error occurs:

```txt
error[E0308]: mismatched types
  --> src/main.rs:7:19
   |
7  |     let era = Era(tinystr!(16, "reiwa"));
   |                   ^^^^^^^^^^^^^^^^^^^^^ expected `tinystr::ascii::TinyAsciiStr<16>`, found `TinyAsciiStr<16>`
   |
   = note: `TinyAsciiStr<16>` and `tinystr::ascii::TinyAsciiStr<16>` have similar names, but are actually distinct types
note: `TinyAsciiStr<16>` is defined in crate `tinystr`
  --> /home/nekevss/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tinystr-0.8.0/src/ascii.rs:14:1
   |
14 | pub struct TinyAsciiStr<const N: usize> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: `tinystr::ascii::TinyAsciiStr<16>` is defined in crate `tinystr`
  --> /home/nekevss/.cargo/git/checkouts/icu4x-5b22b8195fc85e4e/9cb01e4/utils/tinystr/src/ascii.rs:14:1
   |
14 | pub struct TinyAsciiStr<const N: usize> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: perhaps two different versions of crate `tinystr` are being used?
   = note: this error originates in the macro `tinystr` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `icu_calendar::types::Era: From<TinyAsciiStr<16>>` is not satisfied
 --> src/main.rs:8:78
  |
8 |     let era: Era = TinyAsciiStr::<16>::try_from_str("reiwa").expect("value").into();
  |                                                                              ^^^^ the trait `From<TinyAsciiStr<16>>` is not implemented for `icu_calendar::types::Era`, which is required by `TinyAsciiStr<16>: Into<_>`
  |
  = help: the trait `From<tinystr::ascii::TinyAsciiStr<16>>` is implemented for `icu_calendar::types::Era`
  = help: for that trait implementation, expected `tinystr::ascii::TinyAsciiStr<16>`, found `TinyAsciiStr<16>`
  = note: required for `TinyAsciiStr<16>` to implement `Into<icu_calendar::types::Era>`
```

I did confirm this behavior in both `temporal_rs` and a completely new test project, but after looking through both `tinystr` and `icu_calendar`, I'm not entirely sure what could have triggered this to occur. Maybe I'm missing something?

**Comment by nekevss** [comment]
Nevermind. The issue was for some reason using the icu4x git with a tag vs. the published `2.0.0-beta1` version on crates.io
